FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the application distribution to the container
COPY target/universal/play-app-1.0-SNAPSHOT.zip /app

# Unzip the application
RUN apt-get update && apt-get install -y unzip && \
    unzip play-app-1.0-SNAPSHOT.zip && \
    rm play-app-1.0-SNAPSHOT.zip && \
    mv play-app-1.0-SNAPSHOT/* . && \
    rm -r play-app-1.0-SNAPSHOT

# Expose the application port
EXPOSE 9000

# Run the application
CMD ["bin/play-app", "-Dplay.http.secret.key=${PLAY_APP_SECRET}"]